### ISSUE TITLE
Setup the initial template

### ISSUE THREAD

**Issue by alopezag** [alopezag/paper_OA#1]
## ToDo:

- [x] Create the repo
- [x] Link repo to Overleaf template
- [x] Share links with partners 
- [x] Grant access to repo
  + @polbikhan @RMentenUH @shoedt
